### ISSUE TITLE
Simhash returning same value for different length strings

### ISSUE THREAD

**Issue by jishnug007** [1e0ng/simhash#52]
Simhash is returning the same hash value for different strings. 
The strings may contain the same words, but the word count and length of the string are diffrent.
The small reproducible sample is given below,

```
from simhash import Simhash


def get_simhash_value(input: str):
    simhash_value = Simhash(value=input).value
    return simhash_value


res1 = get_simhash_value("test test test test test test test test test test")
res2 = get_simhash_value("test test test test test test test")
print(res1)
print(res2)

```

The original text content is two HTML contents after removing all tags and scripts.

**Comment by 1e0ng** [comment]
Those two strings provided in your example, look very similar, so I would argue this is a feature instead of a bug given the purpose of this library is to find how similar two texts are.
