### ISSUE TITLE
How to use simhash() to check the similarity of different .html files？

### ISSUE THREAD

**Issue by Young-SEU** [1e0ng/simhash#60]
Recently, I am studying how to use the simhash algorithm to check duplicates among a large number of .html files to identify whether different websites are duplicate websites.But I observed that the simhash package you provided seems to only support adding text directly to the code to calculate the simhash value to determine whether it is similar.And I want to ask how can I use your package to check duplicates between different .html files.

**Comment by 1e0ng** [comment]
Hi, in my understanding, simhash cares more about the text content than the display format, so maybe it's a good idea to extract the text content from .html files? Would that make sense to you? There are some libraries that can do this extraction, for example, BeautifulSoup.

**Comment by 1e0ng** [comment]
Hi, I'm closing the issue since not heard back from you for a long time.
