### ISSUE TITLE
Usage of `collections.Iterable` which is absent in Python 3.10

### ISSUE THREAD

**Issue by dluciv** [1e0ng/simhash#62]
Hello, thank you for your beautiful library!

In Python 3.9+ (corrected: 3.10!) `collections` module does not contain `Iterable`. It is deprecated since Python 3.3, and `collections.abc.Iterable` is suggested to be used instead.

It is used in the code though: https://github.com/1e0ng/simhash/blob/8987a06d7afeee0e00b520bbd53a415cf8d85a7a/simhash/__init__.py#L75, which causes a crash.

**Comment by 1e0ng** [comment]
Hi, by Python 3.9+ do you mean 3.10?

I can see the CI passes for Python 3.9 here: https://github.com/1e0ng/simhash/blob/master/.github/workflows/main.yml#L11

**Comment by dluciv** [comment]
Hello!

I tested on 3.10, but before, on 3.8, using `collections.Iterable` caused deprecation warning on removing it since 3.9. If it still works in 3.9, then sorry, 3.10+ =).

**Comment by dluciv** [comment]
Than you!
