### ISSUE TITLE
Delete this line

### ISSUE THREAD

**Issue by GoingMyWay** [1e0ng/simhash#69]
Dear author,

Could you please delete this line, https://github.com/1e0ng/simhash/blob/master/simhash/__init__.py#L210 ? I think there is no need to print all the debug information

**Comment by 1e0ng** [comment]
I'm sorry I won't delete that line because it's for debugging purposes. Users who don't need it can pass in a custom logger that does nothing.

**Comment by GoingMyWay** [comment]
> 

Thanks for your reply. I will try to use a custom logger to override it.
